//----------------------------------------------------------------------------
// copyright (c) 1998, 1999, 2000 Thai Open Source Software Center Ltd
//                                and Clark Cooper
// copyright (c) 2001, 2002, 2003, 2004, 2005, 2006 Expat maintainers.
//
// Expat - Version 2.0.0 Release Milano 0.83 (PasExpat 2.0.0 RM0.83)
// Pascal Port By: Milan Marusinec alias Milano
//                 milan@marusinec.sk
//                 http://www.pasports.org/pasexpat
// copyright (c) 2006
//
// Permission is hereby granted, free of charge, to any person obtaining
// a Copy of this software and associated documentation files (the
// "Software"), to deal in the Software without restriction, including
// without limitation the rights to use, Copy, modify, merge, publish,
// distribute, sublicense, and/or sell copies of the Software, and to
// permit persons to whom the Software is furnished to do so, subject to
// the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR copyright HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
// [Pascal Port History] -----------------------------------------------------
//
// 17.05.2006-Milano: Unit port establishment
//

  ASCII_A = AnsiChar($41);
  ASCII_B = AnsiChar($42);
  ASCII_C = AnsiChar($43);
  ASCII_D = AnsiChar($44);
  ASCII_E = AnsiChar($45);
  ASCII_F = AnsiChar($46);
  ASCII_G = AnsiChar($47);
  ASCII_H = AnsiChar($48);
  ASCII_I = AnsiChar($49);
  ASCII_J = AnsiChar($4A);
  ASCII_K = AnsiChar($4B);
  ASCII_L = AnsiChar($4C);
  ASCII_M = AnsiChar($4D);
  ASCII_N = AnsiChar($4E);
  ASCII_O = AnsiChar($4F);
  ASCII_P = AnsiChar($50);
  ASCII_Q = AnsiChar($51);
  ASCII_R = AnsiChar($52);
  ASCII_S = AnsiChar($53);
  ASCII_T = AnsiChar($54);
  ASCII_U = AnsiChar($55);
  ASCII_V = AnsiChar($56);
  ASCII_W = AnsiChar($57);
  ASCII_X = AnsiChar($58);
  ASCII_Y = AnsiChar($59);
  ASCII_Z = AnsiChar($5A);

  ASCII_al = AnsiChar($61);
  ASCII_bl = AnsiChar($62);
  ASCII_cl = AnsiChar($63);
  ASCII_dl = AnsiChar($64);
  ASCII_el = AnsiChar($65);
  ASCII_fl = AnsiChar($66);
  ASCII_gl = AnsiChar($67);
  ASCII_hl = AnsiChar($68);
  ASCII_il = AnsiChar($69);
  ASCII_jl = AnsiChar($6A);
  ASCII_kl = AnsiChar($6B);
  ASCII_ll = AnsiChar($6C);
  ASCII_ml = AnsiChar($6D);
  ASCII_nl = AnsiChar($6E);
  ASCII_ol = AnsiChar($6F);
  ASCII_pl = AnsiChar($70);
  ASCII_ql = AnsiChar($71);
  ASCII_rl = AnsiChar($72);
  ASCII_sl = AnsiChar($73);
  ASCII_tl = AnsiChar($74);
  ASCII_ul = AnsiChar($75);
  ASCII_vl = AnsiChar($76);
  ASCII_wl = AnsiChar($77);
  ASCII_xl = AnsiChar($78);
  ASCII_yl = AnsiChar($79);
  ASCII_zl = AnsiChar($7A);

  ASCII_0 = AnsiChar($30);
  ASCII_1 = AnsiChar($31);
  ASCII_2 = AnsiChar($32);
  ASCII_3 = AnsiChar($33);
  ASCII_4 = AnsiChar($34);
  ASCII_5 = AnsiChar($35);
  ASCII_6 = AnsiChar($36);
  ASCII_7 = AnsiChar($37);
  ASCII_8 = AnsiChar($38);
  ASCII_9 = AnsiChar($39);

  ASCII_TAB        = AnsiChar($09);
  ASCII_SPACE      = AnsiChar($20);
  ASCII_EXCL       = AnsiChar($21);
  ASCII_QUOT       = AnsiChar($22);
  ASCII_AMP        = AnsiChar($26);
  ASCII_APOS       = AnsiChar($27);
  ASCII_MINUS      = AnsiChar($2D);
  ASCII_PERIOD     = AnsiChar($2E);
  ASCII_COLON      = AnsiChar($3A);
  ASCII_SEMI       = AnsiChar($3B);
  ASCII_LT         = AnsiChar($3C);
  ASCII_EQUALS     = AnsiChar($3D);
  ASCII_GT         = AnsiChar($3E);
  ASCII_LSQB       = AnsiChar($5B);
  ASCII_RSQB       = AnsiChar($5D);
  ASCII_UNDERSCORE = AnsiChar($5F);
