program Project1;

uses
  FMX.Forms,
  Unit1 in 'Unit1.pas' {Form1},
  FMX.Canvas.AggPas in '..\..\FMX.Canvas.AggPas.pas',
  Agg2D in '..\..\..\Agg2D.pas',
  AggArray in '..\..\..\AggArray.pas',
  AggConvCurve in '..\..\..\AggConvCurve.pas',
  AggConvDash in '..\..\..\AggConvDash.pas',
  AggConvStroke in '..\..\..\AggConvStroke.pas',
  AggConvTransform in '..\..\..\AggConvTransform.pas',
  AggMath in '..\..\..\AggMath.pas',
  AggPathStorage in '..\..\..\AggPathStorage.pas',
  AggRendererBase in '..\..\..\AggRendererBase.pas',
  AggRendererScanLine in '..\..\..\AggRendererScanLine.pas',
  AggRenderingBuffer in '..\..\..\AggRenderingBuffer.pas',
  AggSpanConverter in '..\..\..\AggSpanConverter.pas',
  AggSpanGradient in '..\..\..\AggSpanGradient.pas',
  AggSpanImageFilterRgba in '..\..\..\AggSpanImageFilterRgba.pas',
  AggSpanImageResampleRgba in '..\..\..\AggSpanImageResampleRgba.pas',
  AggSpanPattern in '..\..\..\AggSpanPattern.pas',
  AggSpanPatternFilterRgba in '..\..\..\AggSpanPatternFilterRgba.pas',
  AggSpanPatternRgba in '..\..\..\AggSpanPatternRgba.pas',
  AggTransAffine in '..\..\..\AggTransAffine.pas',
  AggTransViewport in '..\..\..\AggTransViewport.pas',
  AggBasics in '..\..\..\AggBasics.pas',
  AggVertexSequence in '..\..\..\AggVertexSequence.pas',
  AggVertexSource in '..\..\..\AggVertexSource.pas',
  AggConvAdaptorVcgen in '..\..\..\AggConvAdaptorVcgen.pas',
  AggVcgenStroke in '..\..\..\AggVcgenStroke.pas',
  AggMathStroke in '..\..\..\AggMathStroke.pas',
  AggShortenPath in '..\..\..\AggShortenPath.pas',
  AggCurves in '..\..\..\AggCurves.pas',
  AggVcgenDash in '..\..\..\AggVcgenDash.pas',
  AggColor in '..\..\..\AggColor.pas',
  AggPixelFormat in '..\..\..\AggPixelFormat.pas',
  AggRasterizerCompoundAA in '..\..\..\AggRasterizerCompoundAA.pas',
  AggRasterizerScanLine in '..\..\..\AggRasterizerScanLine.pas',
  AggScanline in '..\..\..\AggScanline.pas',
  AggScanlineBin in '..\..\..\AggScanlineBin.pas',
  AggScanlinePacked in '..\..\..\AggScanlinePacked.pas',
  AggSpanAllocator in '..\..\..\AggSpanAllocator.pas',
  AggSpanGenerator in '..\..\..\AggSpanGenerator.pas',
  AggRasterizerCellsAA in '..\..\..\AggRasterizerCellsAA.pas',
  AggRasterizerScanlineClip in '..\..\..\AggRasterizerScanlineClip.pas',
  AggClipLiangBarsky in '..\..\..\AggClipLiangBarsky.pas',
  AggSpanInterpolatorLinear in '..\..\..\AggSpanInterpolatorLinear.pas',
  AggDdaLine in '..\..\..\AggDdaLine.pas',
  AggImageFilters in '..\..\..\AggImageFilters.pas',
  AggSpanImageFilter in '..\..\..\AggSpanImageFilter.pas',
  AggSpanImageResample in '..\..\..\AggSpanImageResample.pas',
  AggPixelFormatRgba in '..\..\..\AggPixelFormatRgba.pas',
  AggRasterizerScanLineAA in '..\..\..\AggRasterizerScanLineAA.pas',
  AggGammaFunctions in '..\..\..\AggGammaFunctions.pas',
  AggGammaLUT in '..\..\..\AggGammaLUT.pas',
  AggArc in '..\..\..\AggArc.pas',
  AggBezierArc in '..\..\..\AggBezierArc.pas',
  AggFontCacheManager in '..\..\..\AggFontCacheManager.pas',
  AggFontEngine in '..\..\..\AggFontEngine.pas',
  AggFontFreetype in '..\..\..\AggFontFreetype.pas',
  AggFontFreetypeLib in '..\..\..\AggFontFreetypeLib.pas',
  AggRoundedRect in '..\..\..\AggRoundedRect.pas',
  AggScanlineUnpacked in '..\..\..\AggScanlineUnpacked.pas',
  AggAlphaMaskUnpacked8 in '..\..\..\AggAlphaMaskUnpacked8.pas',
  AggScanlineStorageAA in '..\..\..\AggScanlineStorageAA.pas',
  AggScanlineStorageBin in '..\..\..\AggScanlineStorageBin.pas',
  AggRenderScanlines in '..\..\..\AggRenderScanlines.pas',
  AggPathStorageInteger in '..\..\..\AggPathStorageInteger.pas',
  AggBitsetIterator in '..\..\..\AggBitsetIterator.pas',
  AggFontWin32TrueType in '..\..\..\AggFontWin32TrueType.pas',
  AggConvContour in '..\..\..\AggConvContour.pas',
  AggVcgenContour in '..\..\..\AggVcgenContour.pas';

{$R *.res}

begin
  ReportMemoryLeaksOnShutDown := DebugHook <> 0;

  Application.Initialize;
  Application.CreateForm(TForm1, Form1);
  Application.Run;
end.
